# Generated by Django 5.0.1 on 2024-01-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_alter_city_state_alter_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to=settings.AUTH_USER_MODEL),
        ),
    ]
